import React from "react"
import Head from "next/head"
import styled from "styled-components"

const StyledWrapper = styled.div`
  background: #fffcf9;
`

type Props = {
  children: React.ReactChild
}

const Layout = (props: Props) => {
  const { children } = props

  return (
    <StyledWrapper>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {children}
    </StyledWrapper>
  )
}

export default Layout
